#!/bin/sh

parser="java -cp /home/attomarks/github/my-compiler:/home/attomarks/github/my-compiler/generated Compiler "
if [ $# -eq 2 ]
then 
	file=$2
	option=$1
	blank=" "
	command=${parser}${option}${blank}${file}
	eval $command
elif [ $# -eq 1 ]
then
	file=$1
	command=${parser}${file}
	eval $command
else
	echo "Command Error"
fi
